# Generated by Django 5.0 on 2023-12-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_bulletin_created_at_bulletin_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='category_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bulletins.category'),
            preserve_default=False,
        ),
    ]
