# Generated by Django 5.0 on 2023-12-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_alter_bulletin_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='category',
        ),
    ]
