# Generated by Django 5.0 on 2023-12-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0005_bulletin_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='category_ptr',
        ),
    ]
