# Generated by Django 5.0 on 2023-12-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0006_remove_bulletin_category_ptr_bulletin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
